export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';

/*
export const LOAD_COURSES_SUCCESS = 'LOAD_COURSES_SUCCESS';
export const LOAD_AUTHORS_SUCCESS = 'LOAD_AUTHORS_SUCCESS';
export const CREATE_COURSE_SUCCESS = 'CREATE_COURSE_SUCCESS';
export const UPDATE_COURSE_SUCCESS = 'UPDATE_COURSE_SUCCESS';
*/

// actions for schedules and chat
/*
export const LOAD_CHAT = 'LOAD_CHAT'; 
export const LOAD_SCHEDULE = 'LOAD_SCHEDULE'; 
export const LOAD_TODO = 'LOAD_TODO'; 
*/
export const LOAD_CHAT = 'LOAD_CHAT_SUCCESS'; 
export const ADD_CHAT = 'ADD_CHAT_SUCCESS'; 
export const LOAD_SCHEDULE = 'LOAD_SCHEDULE_SUCCESS'; 
export const ADD_SCHEDULE = 'ADD_SCHEDULE_SUCCESS'; 
export const DELETE_SCHEDULE = 'DELETE_SCHEDULE_SUCCESS'; 
export const EDIT_SCHEDULE = 'EDIT_SCHEDULE_SUCCESS'; 
export const LOAD_PROGRESS = 'LOAD_PROGRESS_SUCCESS'; 

export const LOAD_GUIDE_SUCCESS = 'LOAD_GUIDE_SUCCESS';
export const CREATE_GUIDE_SUCCESS = 'CREATE_GUIDE_SUCCESS';
export const UPDATE_GUIDE_SUCCESS = 'UPDATE_GUIDE_SUCCESS';

export const LOAD_TRIP_SUCCESS = 'LOAD_TRIP_SUCCESS';
export const CREATE_TRIP_SUCCESS = 'CREATE_TRIP_SUCCESS';
export const UPDATE_TRIP_SUCCESS = 'UPDATE_TRIP_SUCCESS';
export const DELETE_TRIP_SUCCESS = 'DELETE_TRIP_SUCCESS';

export const LOAD_PROFILE_SUCCESS = 'LOAD_PROFILE_SUCCESS';
export const CREATE_PROFILE_SUCCESS = 'CREATE_PROFILE_SUCCESS';
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS';
